global:
  scrape_interval: 15s

rule_files:
  - rules.yml

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
    - targets: ['cadvisor:8080']

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

