global:
 resolve_timeout: 5m
 telegram_api_url: "https://api.telegram.org"

templates:
  - './*.tmpl'

receivers:
 - name: telegram-test
   telegram_configs:
    - chat_id: -1002108220805
      bot_token: 6868508217:AAH28TAwepfAe5DngAKtuPnoNfB-0l6wNrY
      api_url: "https://api.telegram.org"
      send_resolved: true
      parse_mode: HTML
      message: '{{ template "telegram.default" . }}'


route:
 group_by: ['alertname']
 group_wait: 15s
 group_interval: 30s
 repeat_interval: 12h
 receiver: telegram-test
 routes:
  - receiver: telegram-test
    continue: true
    matchers:
     - severity="critical"
